"""MyLatestRevision

Revision ID: 3ac4721e0fa1
Revises: 45fedf6bcd81
Create Date: 2017-04-28 06:34:42.924339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac4721e0fa1'
down_revision = '45fedf6bcd81'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
