"""LATESTrevision

Revision ID: 3e08e2e20a2e
Revises: 2fd97a6c96e5
Create Date: 2017-05-05 12:36:17.197438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e08e2e20a2e'
down_revision = '2fd97a6c96e5'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
