"""LATESTestrevision

Revision ID: 59e2668cea98
Revises: 3e08e2e20a2e
Create Date: 2017-05-05 12:39:01.739233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e2668cea98'
down_revision = '3e08e2e20a2e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
