"""LATESTestESTrevision

Revision ID: a5063d71038c
Revises: 59e2668cea98
Create Date: 2017-05-05 12:55:15.546791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5063d71038c'
down_revision = '59e2668cea98'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
